name: Build Executables

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PySide6 opencv-python mediapipe numpy pyinstaller
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name Topini_App --add-data "assets;assets" src/main.py
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: Topini_App_Windows
        path: dist/Topini_App.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PySide6 opencv-python mediapipe numpy pyinstaller
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name Topini_App --add-data "assets:assets" src/main.py
    - name: Upload macOS executable
      uses: actions/upload-artifact@v4
      with:
        name: Topini_App_macOS
        path: dist/Topini_App
